project:
  type: book
  output-dir: docs

book:
  title: "Practical Guide for Statistical Consulting"
  author: "Thiyanga S. Talagala"
  date: ""
  chapters:
    - index.qmd
    - ch1.qmd
    - ch2.qmd
    - ch3.qmd
    - ch4.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

